(()=>{'use strict';
const API=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:3100/api/tools':'https://api.junaf.com/api/tools', root=document.getElementById('main'), nav=document.getElementById('nav'), app=document.getElementById('app'), auth=document.getElementById('auth'), modal=document.getElementById('modal');
const labels={dashboard:'Dashboard',calendar:'Calendar',bookings:'Bookings',projects:'Projects',tasks:'Tasks',finance:'Finance',contacts:'Contacts',schedule:'Schedule'};
// Keep stored enum values and API payloads in English; translate presentation only.
const bilingual={
 'ARTIST BOOKING OS':'JUNAF BOOKING / 档期工作台','Public Performance':'Public Performance / 公开演出','Public Title':'Public Title / 公开标题','Public Description':'Public Description / 公开简介','Ticket / Admission':'Ticket / Admission / 购票及入场方式','Ticket Platform':'Ticket Platform / 售票平台','Ticket URL':'Ticket URL / 购票或预约链接','Ticket Instructions':'Ticket Instructions / 预约或入场说明','Homepage Feature':'Homepage Feature / 可推荐主页','Private':'Private / 不公开','Public':'Public / 公开','Dashboard':'Dashboard / 工作台','Calendar':'Calendar / 日历','Bookings':'Bookings / 预订','Projects':'Projects / 项目','Tasks':'Tasks / 待办','Finance':'Finance / 财务','Contacts':'Contacts / 联系人','Schedule':'Schedule / 日程','Booking Detail':'Booking Detail / 预订详情',
 'Good morning ✨':'Good morning / 早上好 ✨','今天需要关注的安排和待办':'Today’s schedule and actions / 今日安排与待办',
 "Today's Events":"Today's Events / 今日活动",'今天的演出与日程':'Performances and schedule / 演出与日程','Upcoming (7 days)':'Upcoming (7 days) / 未来七天','未来七天 Booking':'Bookings in the next 7 days / 未来七天预订','Pending Actions':'Pending Actions / 待办事项','等待完成的任务':'Tasks to complete / 待完成任务','Outstanding':'Outstanding / 待收款','待收款':'Payments due / 待收款',
 'Today Timeline':'Today Timeline / 今日时间线','View in Calendar':'View in Calendar / 在日历中查看','Finance Snapshot · 本月':'Finance Snapshot · This Month / 本月财务概览','Confirmed Revenue':'Confirmed Revenue / 已确认收入','Received':'Received / 已收款','Expenses':'Expenses / 支出','Estimated Profit':'Estimated Profit / 预估利润','View Finance':'View Finance / 查看财务','Upcoming · Next 7 Days':'Upcoming · Next 7 Days / 未来七天安排','View All':'View All / 查看全部',
 'Booking、排练、演出和个人占用集中查看':'Bookings, rehearsals, performances and personal blocks / 预订、排练、演出与个人占用','Today':'Today / 今天','Month':'Month / 月','Week':'Week / 周','Day':'Day / 日','Timeline':'Timeline / 时间线','Busy':'Busy / 忙碌','Available':'Available / 可用','本月日程':'This Month / 本月日程','完整时间线':'Full Timeline / 完整时间线','暂无安排':'No events / 暂无安排',
 'Title':'Title / 标题','Client':'Client / 客户','Event':'Event / 活动','Status':'Status / 状态','Quote':'Quote / 报价','Project':'Project / 项目','Progress':'Progress / 进度','Final Price':'Final Price / 最终价格','Task':'Task / 任务','Due':'Due / 截止','Priority':'Priority / 优先级','Name':'Name / 姓名','Type':'Type / 类型','Company':'Company / 公司','Phone':'Phone / 电话','Start':'Start / 开始','Payment':'Payment / 收款','Amount':'Amount / 金额','Quick View':'Quick View / 快速查看','Date':'Date / 日期','Venue':'Venue / 场地','Open Detail':'Open Detail / 查看详情','Edit':'Edit / 编辑','条记录':'records / 条记录','选择一条记录查看详情':'Select a record for details / 选择一条记录查看详情','暂无记录，点击右上角新增。':'No records. Use New to create one. / 暂无记录，点击右上角新增。','暂无记录':'No records / 暂无记录',
 '报价、收款与成本概览':'Quotes, payments and costs / 报价、收款与成本概览','Payments':'Payments / 收付款','Booking 不存在':'Booking not found / 预订不存在','Commercial':'Commercial / 商务','Requirements':'Requirements / 需求','Source':'Source / 来源','Created':'Created / 创建时间','Event Date':'Event Date / 活动日期','Start – End':'Start – End / 开始至结束','City':'City / 城市','Client Budget':'Client Budget / 客户预算','暂无需求':'No requirements / 暂无需求','Booking 创建':'Booking created / 创建预订','最近更新':'Last updated / 最近更新','Files':'Files / 文件','文件附件将在后续版本接入。当前可在需求和备注中记录文件链接。':'File attachments are planned for a later version. Add links in requirements or notes for now. / 文件附件将在后续版本接入，当前可在需求或备注中记录链接。',
 '← Back to Bookings':'← Back to Bookings / 返回预订列表','Booking':'Booking / 预订','Hold until':'Hold until / 锁档至','Confirm':'Confirm / 确认','Send Quote':'Copy Quote / 复制报价','View Project':'View Project / 查看项目','Convert to Project':'Convert to Project / 转为项目','Overview':'Overview / 概览','Next Action':'Next Action / 下一步','未设置':'Not set / 未设置','Upcoming Actions':'Upcoming Actions / 即将处理','Quick Info':'Quick Info / 快捷信息','＋ Add Action':'＋ Add Action / 添加待办','Add Payment':'Add Payment / 添加收款',
 'Booking Title':'Booking Title / 预订标题','Select Existing Contact':'Select Existing Contact / 选择已有联系人','Project Type':'Project Type / 项目类型','Event Start':'Event Start / 活动开始','Event End':'Event End / 活动结束','Budget':'Budget / 预算','Hold Until':'Hold Until / 锁档截止','Next Action Due':'Next Action Due / 下一步截止','Description':'Description / 描述','Notes':'Notes / 备注','Project Title':'Project Title / 项目标题','Payment Status':'Payment Status / 收款状态','Event Title':'Event Title / 日程标题','End':'End / 结束','Location':'Location / 地点','Email':'Email / 邮箱','WeChat':'WeChat / 微信','Country':'Country / 国家','Province':'Province / 省份','District':'District / 区县','Address':'Address / 地址','Venue Contact':'Venue Contact / 场地联系人','Parking':'Parking / 停车','Loading':'Loading / 装卸','Due Date':'Due Date / 到期日','Paid Date':'Paid Date / 收款日','Method':'Method / 方式',
 'Inquiry':'Inquiry / 咨询','Tentative':'Tentative / 待定','Hold':'Hold / 锁档','Confirmed':'Confirmed / 已确认','In Progress':'In Progress / 进行中','Completed':'Completed / 已完成','Cancelled':'Cancelled / 已取消','Lost':'Lost / 未成交','Conflict':'Conflict / 冲突','Pending':'Pending / 待处理','Paid':'Paid / 已付款','Overdue':'Overdue / 已逾期','Open':'Open / 未完成','Done':'Done / 已完成','Low':'Low / 低','Medium':'Medium / 中','High':'High / 高','Partial':'Partial / 部分付款','Planning':'Planning / 筹备','Preparation':'Preparation / 准备','Production':'Production / 制作',
 'Meeting':'Meeting / 会议','Travel':'Travel / 出行','Rehearsal':'Rehearsal / 排练','Soundcheck':'Soundcheck / 试音','Performance':'Performance / 演出','Deadline':'Deadline / 截止','Personal Block':'Personal Block / 个人占用','Brand':'Brand / 品牌','Agency':'Agency / 代理机构','Artist':'Artist / 艺术家','Musician':'Musician / 音乐人','Supplier':'Supplier / 供应商','Manager':'Manager / 经纪人','Other':'Other / 其他','Deposit':'Deposit / 定金','Balance':'Balance / 尾款','Full':'Full / 全款','Expense':'Expense / 支出',
 'New Booking':'New Booking / 新建预订','Edit Booking':'Edit Booking / 编辑预订','New Project':'New Project / 新建项目','Edit Project':'Edit Project / 编辑项目','New Event':'New Event / 新建日程','Edit Event':'Edit Event / 编辑日程','New Task':'New Task / 新建待办','Edit Task':'Edit Task / 编辑待办','New Contact':'New Contact / 新建联系人','Edit Contact':'Edit Contact / 编辑联系人','New Payment':'New Payment / 新建收付款','Edit Payment':'Edit Payment / 编辑收付款','当前用户':'当前用户 / 当前 Artist',
 '手动填写客户':'Enter client manually / 手动填写客户','请选择':'Please select / 请选择','取消':'Cancel / 取消','保存':'Save / 保存','请先登录 JUNAF 用户中心':'Please sign in to JUNAF 用户中心 / 请先登录 JUNAF 用户中心','Artist 身份尚未激活':'Artist account is not active / Artist 身份尚未激活','Booking OS 使用你现有的 Artist 账号。':'Booking OS uses your current Artist account. / Booking OS 使用现有 Artist 账号。','前往登录':'Go to sign in / 前往登录','← JUNAF 用户中心':'← JUNAF 用户中心 / 艺术家中心','搜索 Booking、客户、项目…':'Search bookings, clients and projects / 搜索预订、客户和项目…'
};
const bi=s=>bilingual[s]?.split(' / ').at(-1)||s;
function localize(container){
 const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT);
 let node;while((node=walker.nextNode())){const raw=node.nodeValue,key=raw.trim();if(bilingual[key])node.nodeValue=raw.replace(key,bi(key));}
}
const state={view:'dashboard',data:{bookings:[],projects:[],schedule:[],payments:[],contacts:[],tasks:[]},date:new Date(),calendarMode:'Week',detailId:null,contextId:null,detailTab:'Overview',search:'',account:null,modalKind:null,modalId:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,options={})=>v?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'short',day:'numeric',...options}).format(new Date(v)):'—';
const dt=v=>v?new Date(v):null, day=v=>v?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v)):'', money=n=>'¥'+Number(n||0).toLocaleString('zh-CN');
const localInput=v=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const today=()=>day(new Date()); const byId=(kind,id)=>state.data[kind].find(x=>x.id===id);
const sortTime=(a,b)=>new Date(a.eventStart||a.startAt||a.dueAt||a.dueDate||0)-new Date(b.eventStart||b.startAt||b.dueAt||b.dueDate||0);
async function api(path,options={}){const r=await fetch(API+'/booking'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message?(bi(data.message)===data.message?data.message+' / 操作失败，请检查输入或登录状态':bi(data.message)):'Request failed / 操作失败');return data}
function toast(message){const el=document.getElementById('toast');el.textContent=bi(message);localize(el);el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),4800)}
async function refresh(){const d=await api('/bootstrap');for(const k of Object.keys(state.data))state.data[k]=d[k]||[];render()}
function setView(view,id){state.view=view;state.detailId=id||null;state.contextId=null;state.detailTab='Overview';history.replaceState(null,'','#'+view+(id?'/'+id:''));render();document.querySelector('.side').classList.remove('open')}
function row(title,sub,right='',action=''){return `<div class="row ${action?'click':''}" ${action?`data-open="${esc(action)}"`:''}><div class="body"><strong>${esc(title)}</strong><small>${esc(sub)}</small></div>${right}</div>`}
function badge(v){return `<span class="badge ${esc(v)}">${esc(v||'—')}</span>`}
function card(title,body,button=''){return `<section class="card"><div class="card-head"><h2>${esc(title)}</h2>${button}</div>${body||'<div class="empty">暂无记录</div>'}</section>`}
function actionLink(text,view){return `<button class="link" data-view="${view}">${text} →</button>`}
function render(){nav.innerHTML=Object.entries(labels).map(([k,v])=>`<button data-view="${k}" class="${state.view===k?'active':''}">${v}</button>`).join('');document.getElementById('topTitle').textContent=labels[state.view]||'Booking Detail';root.innerHTML=state.detailId&&state.view==='bookings'?renderDetail():state.view==='dashboard'?renderDashboard():state.view==='calendar'?renderCalendar():state.view==='finance'?renderFinance():renderList(state.view);localize(app);}
function renderDashboard(){const now=today(),weekEnd=new Date(Date.now()+7*86400000),active=state.data.bookings.filter(b=>!['Cancelled','Lost'].includes(b.status)),upcoming=active.filter(b=>dt(b.eventStart)>=new Date(now)&&dt(b.eventStart)<weekEnd).sort(sortTime),todayEvents=[...state.data.schedule.filter(s=>day(s.startAt)===now).map(s=>({...s,kind:'schedule'})),...active.filter(b=>day(b.eventStart)===now).map(b=>({...b,kind:'booking'}))].sort(sortTime),tasks=state.data.tasks.filter(t=>t.status!=='Done').sort(sortTime),payments=state.data.payments,received=payments.filter(p=>p.status==='Paid'&&p.type!=='Expense').reduce((n,p)=>n+Number(p.amount||0),0),expenses=payments.filter(p=>p.type==='Expense').reduce((n,p)=>n+Number(p.amount||0),0),revenue=active.filter(b=>['Confirmed','In Progress','Completed'].includes(b.status)).reduce((n,b)=>n+Number(b.quote||0),0),outstanding=payments.filter(p=>p.status!=='Paid'&&p.type!=='Expense'&&p.status!=='Cancelled').reduce((n,p)=>n+Number(p.amount||0),0);
const eventRows=todayEvents.map(x=>`<div class="row click" data-open="${x.kind}:${x.id}"><div class="time">${fmt(x.startAt||x.eventStart,{hour:'2-digit',minute:'2-digit'})}</div><div class="body"><strong>${esc(x.title)}</strong><small>${esc(x.location||x.venue||x.clientName||'')}</small></div>${badge(x.type||x.status)}</div>`).join('');
return `<div class="heading"><div><h1>Good morning ✨</h1><p>今天需要关注的安排和待办</p></div><span class="muted">${fmt(new Date(),{weekday:'long',year:'numeric'})}</span></div><div class="grid metrics"><div class="card metric"><div class="value">${todayEvents.length}</div><div class="label">Today's Events</div><div class="meta">今天的演出与日程</div></div><div class="card metric"><div class="value">${upcoming.length}</div><div class="label">Upcoming (7 days)</div><div class="meta">未来七天 Booking</div></div><div class="card metric"><div class="value">${tasks.length}</div><div class="label">Pending Actions</div><div class="meta">等待完成的任务</div></div><div class="card metric"><div class="value">${money(outstanding)}</div><div class="label">Outstanding</div><div class="meta">待收款</div></div></div><div class="grid dashboard-grid"><div class="stack">${card('Today Timeline',eventRows,actionLink('View in Calendar','calendar'))}${card('Finance Snapshot · 本月',`<div class="finance-strip"><div><strong>${money(revenue)}</strong><small>Confirmed Revenue</small></div><div><strong>${money(received)}</strong><small>Received</small></div><div><strong>${money(outstanding)}</strong><small>Outstanding</small></div><div><strong>${money(expenses)}</strong><small>Expenses</small></div><div><strong>${money(received-expenses)}</strong><small>Estimated Profit</small></div></div>`,actionLink('View Finance','finance'))}</div><div class="stack">${card('Upcoming · Next 7 Days',upcoming.slice(0,6).map(b=>row(b.title,`${fmt(b.eventStart)} · ${b.clientName||b.city||''}`,`${badge(b.status)}　${money(b.quote)}`,'booking:'+b.id)).join(''),actionLink('View All','bookings'))}${card('Pending Actions',tasks.slice(0,6).map(t=>`<div class="row"><input type="checkbox" data-done="${t.id}" style="width:auto"><div class="body"><strong>${esc(t.title)}</strong><small>${esc(t.notes||'')}</small></div><small>${fmt(t.dueAt)}</small></div>`).join(''),actionLink('View All','tasks'))}</div></div>`}
function weekStart(date){const x=new Date(date);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function renderCalendar(){const base=weekStart(state.date),days=Array.from({length:7},(_,i)=>{const x=new Date(base);x.setDate(base.getDate()+i);return x}),sel=day(state.date),events=[...state.data.schedule.map(x=>({...x,when:x.startAt,kind:'schedule'})),...state.data.bookings.filter(x=>!['Cancelled','Lost'].includes(x.status)).map(x=>({...x,when:x.eventStart,kind:'booking'}))],daily=events.filter(x=>day(x.when)===sel).sort((a,b)=>new Date(a.when)-new Date(b.when)),mode=state.calendarMode;
let calendar='';if(mode==='Week'||mode==='Day'){const shown=mode==='Day'?[state.date]:days;calendar=`<div class="card" style="overflow:auto;padding:0"><div class="calendar-grid" style="grid-template-columns:54px repeat(${shown.length},minmax(95px,1fr))"><div class="cal-head"></div>${shown.map(d=>`<div class="cal-head ${day(d)===sel?'selected':''}" data-day="${day(d)}">${fmt(d,{weekday:'short'})}<br>${fmt(d)}</div>`).join('')}${Array.from({length:16},(_,n)=>{const hour=n+7;return `<div class="cal-time">${String(hour).padStart(2,'0')}:00</div>${shown.map(d=>{const hits=events.filter(x=>day(x.when)===day(d)&&new Date(x.when).getHours()===hour);return `<div class="cal-cell" data-day="${day(d)}" data-hour="${hour}">${hits.map(x=>`<div class="cal-event ${x.kind==='booking'?'book':x.type==='Personal Block'?'block':''}" data-open="${x.kind}:${x.id}">${esc(x.title)}</div>`).join('')}</div>`}).join('')}`}).join('')}</div></div>`}else{const list=mode==='Month'?events.filter(x=>new Date(x.when).getMonth()===state.date.getMonth()&&new Date(x.when).getFullYear()===state.date.getFullYear()):events;calendar=card(mode==='Month'?'本月日程':'完整时间线',list.sort((a,b)=>new Date(a.when)-new Date(b.when)).map(x=>row(x.title,`${fmt(x.when,{year:'numeric',hour:'2-digit',minute:'2-digit'})} · ${x.location||x.venue||''}`,badge(x.type||x.status),x.kind+':'+x.id)).join(''))}
return `<div class="heading"><div><h1>Calendar</h1><p>Booking、排练、演出和个人占用集中查看</p></div><button class="btn gold" data-new="schedule">＋ New Event / 新建日程</button></div><div class="calendar-toolbar"><div class="actions"><button class="btn" data-today>Today</button><button class="btn" data-shift="-1">‹</button><button class="btn" data-shift="1">›</button><strong>${fmt(state.date,{month:'long',year:'numeric'})}</strong></div><div class="actions">${['Month','Week','Day','Timeline'].map(m=>`<button class="btn ${mode===m?'gold':''}" data-mode="${m}">${m}</button>`).join('')}</div></div><div class="split">${calendar}<aside class="right-panel">${card(fmt(state.date,{weekday:'long',year:'numeric'}),`<div class="badge">${daily.length?'Busy':'Available'}</div>${daily.map(x=>row(x.title,`${fmt(x.when,{hour:'2-digit',minute:'2-digit'})} · ${x.location||x.venue||''}`,badge(x.type||x.status),x.kind+':'+x.id)).join('')||'<div class="empty">暂无安排</div>'}<div class="actions"><button class="btn" data-new="bookings">New Booking / 新建预订</button><button class="btn" data-new="schedule">Add Event / 添加日程</button><button class="btn" data-block>Block Time / 锁定时间</button></div>`)}</aside></div>`}
function renderList(kind){
 if(!state.data[kind])return '';
 const cols={bookings:['Title','Client','Event','Status','Quote'],projects:['Project','Client','Event','Progress','Final Price'],tasks:['Task','Due','Priority','Status',''],contacts:['Name','Type','Company','Phone',''],schedule:['Event','Type','Start','Status',''],payments:['Payment','Amount','Due','Status','']};
 const rows=state.data[kind].filter(x=>!state.search||JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase())).sort(sortTime);
 const values=x=>kind==='bookings'?[esc(x.title),esc(x.clientName),fmt(x.eventStart,{year:'numeric'}),badge(x.status),money(x.quote)]:kind==='projects'?[esc(x.title),esc(x.clientName),fmt(x.eventStart,{year:'numeric'}),esc(x.progress),money(x.finalPrice)]:kind==='tasks'?[esc(x.title),fmt(x.dueAt),esc(x.priority),badge(x.status),'']:kind==='contacts'?[esc(x.name),esc(x.type),esc(x.company),esc(x.phone),'']:kind==='schedule'?[esc(x.title),esc(x.type),fmt(x.startAt,{hour:'2-digit',minute:'2-digit'}),badge(x.status),'']:[esc(x.type),money(x.amount),fmt(x.dueDate),badge(x.status),''];
 const selected=byId(kind,state.contextId);
 let context=card('Quick View','<div class="empty">选择一条记录查看详情</div>');
 if(selected){
  let body=`<h3>${esc(selected.title||selected.name||selected.type)}</h3>`;
  if(kind==='bookings')body+=kv('Client',esc(selected.clientName))+kv('Date',fmt(selected.eventStart,{year:'numeric'}))+kv('Venue',esc(selected.venue))+kv('Status',badge(selected.status))+kv('Quote',money(selected.quote))+`<div class="actions"><button class="btn" data-detail="${selected.id}">Open Detail</button><button class="btn" data-edit="bookings:${selected.id}">Edit</button></div>`;
  else body+=kv('Status',badge(selected.status))+kv('Date',fmt(selected.startAt||selected.eventStart||selected.dueAt||selected.dueDate))+`<button class="btn" data-edit="${kind}:${selected.id}">Edit</button>`;
  context=card('Quick View',body);
 }
 const head=`<div class="heading"><div><h1>${labels[kind]}</h1><p>${rows.length} records / 条记录</p></div><button class="btn gold" data-new="${kind}">＋ ${bi('New '+(kind==='schedule'?'Event':kind==='tasks'?'Task':kind==='contacts'?'Contact':kind==='payments'?'Payment':kind==='projects'?'Project':'Booking'))}</button></div>`;
 const table=`<div style="overflow:auto"><table class="list-table"><thead><tr>${cols[kind].map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.map(x=>`<tr class="click" data-open="${kind==='bookings'?'booking:':kind+':'}${x.id}">${values(x).map(v=>`<td>${v??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 return head+`<div class="split">${card(labels[kind],table+(!rows.length?'<div class="empty">暂无记录，点击右上角新增。</div>':''))}<aside class="right-panel">${context}</aside></div>`;
}
function renderFinance(){const p=state.data.payments,received=p.filter(x=>x.status==='Paid'&&x.type!=='Expense').reduce((n,x)=>n+Number(x.amount||0),0),due=p.filter(x=>x.status!=='Paid'&&x.type!=='Expense').reduce((n,x)=>n+Number(x.amount||0),0),expenses=p.filter(x=>x.type==='Expense').reduce((n,x)=>n+Number(x.amount||0),0);return `<div class="heading"><div><h1>Finance</h1><p>报价、收款与成本概览</p></div><button class="btn gold" data-new="payments">＋ New Payment / 新建收付款</button></div><div class="grid metrics"><div class="card metric"><div class="value">${money(received)}</div><div class="label">Received</div></div><div class="card metric"><div class="value">${money(due)}</div><div class="label">Outstanding</div></div><div class="card metric"><div class="value">${money(expenses)}</div><div class="label">Expenses</div></div><div class="card metric"><div class="value">${money(received-expenses)}</div><div class="label">Estimated Profit</div></div></div>${card('Payments',p.map(x=>row(x.type||'Payment',`${fmt(x.dueDate)} · ${x.notes||''}`,`${money(x.amount)}　${badge(x.status)}`,'payments:'+x.id)).join(''))}`}
function kv(key,value){return `<div class="kv"><span>${esc(key)}</span><span>${value==null||value===''?'—':value}</span></div>`}
function renderDetail(){const b=byId('bookings',state.detailId);if(!b)return '<div class="empty">Booking 不存在</div>';const client=byId('contacts',b.clientId),tasks=state.data.tasks.filter(t=>t.bookingId===b.id),events=state.data.schedule.filter(s=>s.bookingId===b.id),payments=state.data.payments.filter(p=>p.bookingId===b.id),project=state.data.projects.find(p=>p.bookingId===b.id),tab=state.detailTab;
const overview=`<div class="detail-main">${card('Client',kv('Name',esc(b.clientName||client?.name))+kv('Company',esc(client?.company))+kv('Phone',esc(client?.phone))+kv('Email',esc(client?.email))+kv('WeChat',esc(client?.wechat)),`<button class="link" data-edit="bookings:${b.id}">Edit</button>`)}${card('Booking',kv('Type',esc(b.projectType))+kv('Source',esc(b.source))+kv('Status',badge(b.status))+kv('Priority',esc(b.priority))+kv('Created',fmt(b.createdAt)),`<button class="link" data-edit="bookings:${b.id}">Edit</button>`)}${card('Event',kv('Event Date',fmt(b.eventStart,{year:'numeric'}))+kv('Start – End',`${fmt(b.eventStart,{hour:'2-digit',minute:'2-digit'})} – ${fmt(b.eventEnd,{hour:'2-digit',minute:'2-digit'})}`)+kv('Venue',esc(b.venue))+kv('City',esc(b.city)),`<button class="link" data-edit="bookings:${b.id}">Edit</button>`)}${card('Commercial',kv('Client Budget',money(b.budget))+kv('Quote',money(b.quote))+kv('Project',project?`<button class="link" data-view="projects">${esc(project.title)}</button>`:'—'),`<button class="link" data-edit="bookings:${b.id}">Edit</button>`)}${card('Requirements',`<p>${esc(b.requirements||'暂无需求')}</p><p class="muted">${esc(b.description||'')}</p>`,`<button class="link" data-edit="bookings:${b.id}">Edit</button>`)}</div>`;
const timeline=card('Timeline',[{title:'Booking 创建',when:b.createdAt},{title:'最近更新',when:b.updatedAt},...events.map(x=>({title:x.title,when:x.startAt})),...tasks.map(x=>({title:x.title,when:x.dueAt}))].sort((a,c)=>new Date(a.when)-new Date(c.when)).map(x=>row(x.title,fmt(x.when,{year:'numeric',hour:'2-digit',minute:'2-digit'}))).join(''));
const content=tab==='Overview'?overview:tab==='Timeline'?timeline:tab==='Schedule'?card('Schedule',events.map(x=>row(x.title,`${fmt(x.startAt,{year:'numeric',hour:'2-digit',minute:'2-digit'})} · ${x.location||''}`,badge(x.type),'schedule:'+x.id)).join(''),`<button class="link" data-new="schedule">Add Event / 添加日程</button>`):tab==='Finance'?card('Finance',payments.map(x=>row(x.type||'Payment',fmt(x.dueDate),`${money(x.amount)}　${badge(x.status)}`,'payments:'+x.id)).join(''),`<button class="link" data-new="payments">Add Payment</button>`):card('Files','<div class="empty">文件附件将在后续版本接入。当前可在需求和备注中记录文件链接。</div>');
return `<button class="link" data-view="bookings">← Back to Bookings</button><div class="detail-hero"><div><h1>${esc(b.title)}</h1><p class="muted">${esc(b.projectType||'Booking')} · ${esc(b.clientName||'')} · ${esc(b.city||'')}</p><p>${badge(b.status)}　${fmt(b.eventStart,{year:'numeric'})}　${b.holdUntil?`Hold until / 锁档至 ${fmt(b.holdUntil,{hour:'2-digit',minute:'2-digit'})}`:''}</p></div><div class="actions"><strong style="font-size:24px">${money(b.quote)}</strong><button class="btn" data-edit="bookings:${b.id}">Edit</button><button class="btn gold" data-confirm="${b.id}">Confirm</button><button class="btn" data-quote="${b.id}">Send Quote</button>${b.status==='Confirmed'||b.status==='In Progress'?`<button class="btn" data-convert="${b.id}">${project?'View Project':'Convert to Project'}</button>`:''}</div></div><div class="tabs">${['Overview','Timeline','Schedule','Finance'].map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}">${t}</button>`).join('')}</div><div class="detail-grid"><div>${content}</div><aside class="right-panel">${card('Next Action',`<strong>${esc(b.nextAction||'未设置')}</strong><p class="muted">Due / 截止: ${fmt(b.nextActionDue)}</p><button class="btn" data-edit="bookings:${b.id}">Edit</button>`)}${card('Upcoming Actions',tasks.filter(t=>t.status!=='Done').map(t=>`<div class="row"><input type="checkbox" data-done="${t.id}" style="width:auto"><div class="body"><strong>${esc(t.title)}</strong><small>${fmt(t.dueAt)}</small></div></div>`).join(''),`<button class="link" data-new="tasks">＋ Add Action</button>`)}${card('Quick Info',`<div class="actions"><button class="btn" data-view="calendar">View in Calendar</button><button class="btn" data-new="schedule">Add Event / 添加日程</button><button class="btn" data-new="payments">Add Payment</button></div>`)}</aside></div>`}
const fieldDefs={bookings:[['title','Booking Title','text',1],['clientName','Client','text'],['clientId','Select Existing Contact','select-contact'],['projectType','Project Type','text'],['source','Source','text'],['eventStart','Event Start','datetime-local',1],['eventEnd','Event End','datetime-local'],['venue','Venue','text'],['city','City','text'],['budget','Budget','number'],['quote','Quote','number'],['status','Status','select','Inquiry|Tentative|Hold|Confirmed|In Progress|Completed|Cancelled|Lost'],['holdUntil','Hold Until','datetime-local'],['priority','Priority','select','Low|Medium|High'],['nextAction','Next Action','text'],['nextActionDue','Next Action Due','datetime-local'],['requirements','Requirements','textarea'],['description','Description','textarea'],['notes','Notes','textarea']],projects:[['title','Project Title','text',1],['clientName','Client','text'],['projectType','Type','text'],['eventStart','Event Start','datetime-local'],['eventEnd','Event End','datetime-local'],['venue','Venue','text'],['city','City','text'],['finalPrice','Final Price','number'],['progress','Progress','select','Planning|Preparation|Production|Completed'],['paymentStatus','Payment Status','select','Pending|Partial|Paid'],['requirements','Requirements','textarea'],['notes','Notes','textarea']],schedule:[['title','Event Title','text',1],['type','Type','select','Meeting|Travel|Rehearsal|Soundcheck|Performance|Deadline|Payment|Personal Block'],['startAt','Start','datetime-local',1],['endAt','End','datetime-local'],['location','Location','text'],['status','Status','select','Available|Inquiry|Tentative|Hold|Confirmed|In Progress|Completed|Conflict'],['notes','Notes','textarea']],tasks:[['title','Task','text',1],['dueAt','Due','datetime-local'],['priority','Priority','select','Low|Medium|High'],['status','Status','select','Open|Done'],['notes','Notes','textarea']],contacts:[['name','Name','text',1],['type','Type','select','Client|Brand|Agency|Venue|Artist|Musician|Supplier|Manager|Other'],['company','Company','text'],['phone','Phone','text'],['email','Email','email'],['wechat','WeChat','text'],['country','Country','text'],['province','Province','text'],['city','City','text'],['district','District','text'],['address','Address','text'],['contact','Venue Contact','text'],['parking','Parking','text'],['loading','Loading','text'],['notes','Notes','textarea']],payments:[['type','Type','select','Deposit|Balance|Full|Expense|Other'],['amount','Amount','number',1],['dueDate','Due Date','date'],['paidDate','Paid Date','date'],['status','Status','select','Pending|Paid|Overdue|Cancelled'],['paymentMethod','Method','text'],['notes','Notes','textarea']]};
function openForm(kind,id,defaults={}){
 const item=id?byId(kind,id):defaults;
 state.modalKind=kind;state.modalId=id||null;
 document.getElementById('modalTitle').textContent=(id?'编辑 ':'新建 ')+({schedule:'日程',tasks:'待办',contacts:'联系人',payments:'收付款',projects:'项目',bookings:'预约'}[kind]);
 document.getElementById('modalError').textContent='';
 document.getElementById('modalFields').innerHTML=fieldDefs[kind].map(([key,label,type,extra])=>{
  const value=item?.[key]??'',required=extra===1?'required':'';
  const control=type==='select-contact'?`<select name="${key}"><option value="">手动填写客户</option>${state.data.contacts.map(c=>`<option value="${esc(c.id)}" ${value===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select>`
   :type==='select'?`<select name="${key}"><option value="">请选择</option>${String(extra||'').split('|').filter(Boolean).map(o=>`<option value="${esc(o)}" ${value===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`
   :type==='textarea'?`<textarea name="${key}">${esc(value)}</textarea>`
   :`<input name="${key}" type="${type}" value="${esc(type==='datetime-local'?localInput(value):type==='date'?String(value).slice(0,10):value)}" ${required} ${type==='number'?'min="0" step="0.01"':''}>`;
  return `<label class="${type==='textarea'?'wide':''}">${label}${control}</label>`;
 }).join('');
 modal.showModal();localize(modal);
}
async function saveForm(e){
 e.preventDefault();
 const kind=state.modalKind,id=state.modalId,data=Object.fromEntries(new FormData(e.target).entries());
 const errorBox=document.getElementById('modalError');errorBox.textContent='';
 for(const [key,,type] of fieldDefs[kind]){
  if(data[key]==='') {if(!id)delete data[key];continue;}
  if(type==='datetime-local')data[key]=new Date(data[key]).toISOString();
  else if(type==='number')data[key]=Number(data[key]);
 }
 if(kind==='bookings'&&data.clientId&&!data.clientName)data.clientName=byId('contacts',data.clientId)?.name||'';
 if(!id&&state.detailId&&['schedule','tasks','payments'].includes(kind))data.bookingId=state.detailId;
 try{
  const result=await api('/'+kind+(id?'/'+id:''),{method:id?'PATCH':'POST',body:JSON.stringify(data)});
  await refresh();modal.close();
  toast(result.warnings?.length?`已保存；发现 ${result.warnings.length} 个日程冲突，请检查日历。`:'已保存');
  if(kind==='bookings'&&!id)setView('bookings',result.item.id);
 }catch(error){errorBox.textContent=error.message;errorBox.scrollIntoView({block:'center',behavior:'smooth'});}
}
async function patch(kind,id,data){try{const r=await api('/'+kind+'/'+id,{method:'PATCH',body:JSON.stringify(data)});await refresh();toast(r.warnings?.length?`Saved. ${r.warnings.length} conflicts. / 已保存，发现 ${r.warnings.length} 个冲突。`:'Updated / 已更新')}catch(e){toast(e.message)}}
document.addEventListener('click',async e=>{const t=e.target.closest('button,[data-open],[data-day],[data-hour],[data-done]');if(!t)return;if(t.dataset.view){setView(t.dataset.view);return}if(t.dataset.open){e.stopPropagation();const [kind,id]=t.dataset.open.split(':');if(kind==='booking'||kind==='bookings'){if(state.view==='bookings'&&!state.detailId){if(state.contextId===id)setView('bookings',id);else{state.contextId=id;render()}}else setView('bookings',id)}else if(state.data[kind]){if(state.view===kind){state.contextId=id;render()}else openForm(kind,id)}return}if(t.dataset.detail){setView('bookings',t.dataset.detail);return}if(t.dataset.new){openForm(t.dataset.new);return}if(t.dataset.edit){const [kind,id]=t.dataset.edit.split(':');openForm(kind,id);return}if(t.dataset.done){await patch('tasks',t.dataset.done,{status:'Done'});return}if(t.dataset.confirm){await patch('bookings',t.dataset.confirm,{status:'Confirmed'});return}if(t.dataset.convert){try{const r=await api('/bookings/'+t.dataset.convert+'/convert',{method:'POST'});await refresh();toast('Project created / 已创建项目：'+r.project.title);setView('projects')}catch(err){toast(err.message)}return}if(t.dataset.quote){const b=byId('bookings',t.dataset.quote),quote=`${b.title}\n客户：${b.clientName||'—'}\n日期：${fmt(b.eventStart,{year:'numeric'})}\n报价：${money(b.quote)}`;try{await navigator.clipboard.writeText(quote);toast('Quote copied. Paste it into email or chat to send. / 报价已复制，请粘贴到邮件或聊天工具发送。')}catch{toast('Copy failed. See the quote in Booking details. / 复制失败，请在预订详情中查看报价。')}return}if(t.dataset.tab){state.detailTab=t.dataset.tab;render();return}if(t.dataset.mode){state.calendarMode=t.dataset.mode;render();return}if(t.dataset.today!==undefined){state.date=new Date();render();return}if(t.dataset.shift){const x=new Date(state.date);x.setDate(x.getDate()+Number(t.dataset.shift)*(state.calendarMode==='Week'?7:state.calendarMode==='Month'?30:1));state.date=x;render();return}if(t.dataset.day){state.date=new Date(t.dataset.day+'T12:00:00');render();return}if(t.dataset.block!==undefined){openForm('schedule',null,{type:'Personal Block',title:'Personal Block / 个人占用',startAt:state.date});return}});
document.getElementById('newButton').onclick=()=>openForm('bookings');document.getElementById('mobileMenu').onclick=()=>document.querySelector('.side').classList.toggle('open');document.getElementById('search').oninput=e=>{state.search=e.target.value;if(['bookings','projects','tasks','contacts','schedule'].includes(state.view))render()};document.getElementById('modalForm').onsubmit=saveForm;document.getElementById('closeModal').onclick=document.getElementById('cancelModal').onclick=()=>modal.close();
async function init(){
 try{
  const authApi=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:3100/api/auth/me':'https://api.junaf.com/api/auth/me';
  const response=await fetch(authApi,{credentials:'include',cache:'no-store'});
  if(!response.ok)throw Error('请先登录 JUNAF 账号');
  const data=await response.json();if(!data.ok||!data.account)throw Error('请先登录 JUNAF 账号');
  state.account=data.account;
  document.getElementById('accountName').textContent=data.account.displayName||data.account.email;
  app.hidden=false;auth.hidden=true;
  const hash=location.hash.slice(1).split('/');if(labels[hash[0]]){state.view=hash[0];state.detailId=hash[1]||null;}
  await refresh();
 }catch(error){app.hidden=true;auth.hidden=false;auth.querySelector('p').textContent=error.message;}
}
init();
})();
