'use strict';
const express=require('express');
const crypto=require('node:crypto');
const {currentAccount}=require('./auth');
const clean=(value,max)=>String(value||'').trim().slice(0,max);
const idOk=id=>/^[a-f0-9]{32}$/.test(String(id));
const same=(x,y)=>String(x)===String(y);
const isAdmin=a=>!!process.env.JUNAF_ADMIN_EMAIL&&a?.emailLower===process.env.JUNAF_ADMIN_EMAIL.trim().toLowerCase();
const summary=p=>({id:p._id,title:p.title,category:p.category,excerpt:p.body.slice(0,180),authorName:p.authorName,artistLevel:p.artistLevel,status:p.status,createdAt:p.createdAt,publishedAt:p.publishedAt,updatedAt:p.updatedAt});
module.exports=function createThinkingRouter(db){
  const router=express.Router(),artists=db.collection('junaf_artists'),posts=db.collection('junaf_thinking_posts'),usage=db.collection('junaf_artist_daily_thinking_posts');
  async function identity(req,res,next){try{req.account=await currentAccount(db,req);req.isAdmin=isAdmin(req.account);next();}catch(e){console.error('thinking auth:',e);res.status(503).json({ok:false,message:'账号验证暂不可用'});}}
  const login=(req,res)=>{if(req.account)return true;res.status(401).json({ok:false,message:'请先登录 JUNAF'});return false;};
  const admin=(req,res)=>{if(req.isAdmin)return true;res.status(403).json({ok:false,message:'需要管理员身份'});return false;};
  router.get('/posts',async(req,res)=>{try{const query={status:'published'},category=clean(req.query.category,60),q=clean(req.query.q,80);if(category)query.category=category;if(q)query.$or=['title','category','authorName','body'].map(k=>({[k]:{$regex:q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'}}));const rows=await posts.find(query).sort({publishedAt:-1}).limit(100).toArray();res.set('Cache-Control','public, max-age=30');res.json({ok:true,posts:rows.map(summary)});}catch{res.status(503).json({ok:false,message:'思考目录暂不可用'});}});
  router.get('/posts/:id',identity,async(req,res)=>{if(!idOk(req.params.id))return res.sendStatus(404);try{const p=await posts.findOne({_id:req.params.id});if(!p||(p.status!=='published'&&!req.isAdmin&&!same(p.accountId,req.account?._id)))return res.sendStatus(404);res.set('Cache-Control',p.status==='published'?'public, max-age=60':'private, no-store');res.json({ok:true,post:{...summary(p),body:p.body}});}catch{res.status(503).json({ok:false,message:'文章暂不可用'});}});
  router.use(identity);
  router.get('/studio',async(req,res)=>{if(!login(req,res))return;try{const artist=await artists.findOne({_id:req.account._id}),rows=await posts.find({accountId:req.account._id}).sort({updatedAt:-1}).limit(100).toArray(),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),used=await usage.findOne({_id:`${req.account._id}:${day}`});res.json({ok:true,isAdmin:req.isAdmin,artist:artist?{name:artist.name,status:artist.status,level:artist.level||'A1',dailyThinkingLimit:artist.dailyThinkingLimit??3}:null,usedToday:used?.count||0,posts:rows.map(p=>({...summary(p),body:p.body}))});}catch{res.status(503).json({ok:false,message:'写作工作室暂不可用'});}});
  router.post('/posts',express.json({limit:'48kb'}),async(req,res)=>{if(!login(req,res))return;const artist=await artists.findOne({_id:req.account._id});if(!req.isAdmin&&artist?.status!=='approved')return res.status(403).json({ok:false,message:'请先获得 JUNAF 艺术家资格'});const title=clean(req.body?.title,160),category=clean(req.body?.category,60),body=clean(req.body?.body,20000);if(!title||!category||body.length<20)return res.status(400).json({ok:false,message:'请填写标题、类别和至少20字正文'});const id=crypto.randomBytes(16).toString('hex'),now=new Date();try{await posts.insertOne({_id:id,accountId:req.account._id,title,category,body,authorName:artist?.name||req.account.displayName||'JUNAF',artistLevel:artist?.level||'A1',status:'draft',createdAt:now,updatedAt:now});res.status(201).json({ok:true,id,message:'草稿已保存'});}catch{res.status(503).json({ok:false,message:'保存草稿失败'});}});
  router.patch('/posts/:id',express.json({limit:'48kb'}),async(req,res)=>{if(!login(req,res))return;if(!idOk(req.params.id))return res.sendStatus(404);const p=await posts.findOne({_id:req.params.id});if(!p||(!req.isAdmin&&!same(p.accountId,req.account._id)))return res.sendStatus(404);const title=clean(req.body?.title,160),category=clean(req.body?.category,60),body=clean(req.body?.body,20000);if(!title||!category||body.length<20)return res.status(400).json({ok:false,message:'请填写标题、类别和至少20字正文'});const set={title,category,body,updatedAt:new Date()};if(p.status==='published')set.status='pending';else if(p.status==='rejected')set.status='draft';await posts.updateOne({_id:p._id},{$set:set});res.json({ok:true,status:set.status||p.status});});
  router.delete('/posts/:id',async(req,res)=>{if(!login(req,res))return;if(!idOk(req.params.id))return res.sendStatus(404);try{const p=await posts.findOne({_id:req.params.id});if(!p||(!req.isAdmin&&!same(p.accountId,req.account._id)))return res.sendStatus(404);if(!['draft','rejected'].includes(p.status))return res.status(409).json({ok:false,message:'只能删除草稿或未通过的文章'});const result=await posts.deleteOne({_id:p._id,status:p.status});if(!result.deletedCount)return res.status(409).json({ok:false,message:'文章状态已变化，请刷新'});res.json({ok:true,message:'草稿已删除'});}catch(e){console.error('thinking delete:',e);res.status(503).json({ok:false,message:'删除暂不可用'});}});
  router.post('/posts/:id/submit',async(req,res)=>{if(!login(req,res))return;if(!idOk(req.params.id))return res.sendStatus(404);const p=await posts.findOne({_id:req.params.id});if(!p||!same(p.accountId,req.account._id))return res.sendStatus(404);if(!['draft','rejected'].includes(p.status))return res.status(409).json({ok:false,message:'当前文章无需重复投稿'});const artist=await artists.findOne({_id:req.account._id});if(!req.isAdmin&&artist?.status!=='approved')return res.status(403).json({ok:false,message:'艺术家资格尚未获批'});let reserved=false,day='';try{if(!req.isAdmin){day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const key=`${req.account._id}:${day}`,limit=Math.max(0,Math.min(1000,Number(artist.dailyThinkingLimit??3)));await usage.updateOne({_id:key},{$setOnInsert:{count:0,accountId:req.account._id,day}},{upsert:true});const result=await usage.updateOne({_id:key,count:{$lt:limit}},{$inc:{count:1}});if(!result.matchedCount)return res.status(429).json({ok:false,message:`今天投稿已达 ${limit} 篇上限`});reserved=true;}const result=await posts.updateOne({_id:p._id,status:p.status},{$set:{status:'pending',submittedAt:new Date(),updatedAt:new Date()}});if(!result.matchedCount){if(reserved)await usage.updateOne({_id:`${req.account._id}:${day}`},{$inc:{count:-1}});return res.status(409).json({ok:false,message:'文章状态已变化，请刷新'});}res.json({ok:true,message:'已提交审核'});}catch(e){if(reserved)await usage.updateOne({_id:`${req.account._id}:${day}`},{$inc:{count:-1}}).catch(()=>{});res.status(503).json({ok:false,message:'提交暂不可用'});}});
  router.get('/admin/posts',async(req,res)=>{if(!admin(req,res))return;const rows=await posts.find({}).sort({updatedAt:-1}).limit(200).toArray();res.json({ok:true,posts:rows.map(p=>({...summary(p),body:p.body}))});});
  router.patch('/admin/posts/:id',express.json({limit:'8kb'}),async(req,res)=>{if(!admin(req,res))return;if(!idOk(req.params.id)||!['published','rejected','pending'].includes(req.body?.status))return res.sendStatus(400);const set={status:req.body.status,updatedAt:new Date()};if(set.status==='published')set.publishedAt=new Date();const result=await posts.updateOne({_id:req.params.id},{$set:set});if(!result.matchedCount)return res.sendStatus(404);res.json({ok:true});});
  router.get('/admin/artists',async(req,res)=>{if(!admin(req,res))return;const rows=await artists.find({}).sort({updatedAt:-1}).limit(200).toArray();res.json({ok:true,artists:rows.map(a=>({id:String(a._id),name:a.name,status:a.status,level:a.level||'A1',dailyThinkingLimit:a.dailyThinkingLimit??3}))});});
  router.patch('/admin/artists/:id',express.json({limit:'8kb'}),async(req,res)=>{if(!admin(req,res))return;const {ObjectId}=require('mongodb');let id;try{id=new ObjectId(req.params.id);}catch{return res.sendStatus(400);}const limit=req.body?.dailyThinkingLimit;if(!Number.isInteger(limit)||limit<0||limit>1000)return res.sendStatus(400);const result=await artists.updateOne({_id:id},{$set:{dailyThinkingLimit:limit,updatedAt:new Date()}});if(!result.matchedCount)return res.sendStatus(404);res.json({ok:true});});
  return router;
};
