(()=>{'use strict';
const BASE=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:3100/api':'https://api.junaf.com/api';
const $=id=>document.getElementById(id);
let busy=false, jobs=[];
async function api(path,options={}){const response=await fetch(BASE+path,{credentials:'include',cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.message||'请求失败');return data}
function status(message){$('status').textContent=message}
function render(){const list=$('job-list');list.replaceChildren();if(!jobs.length){const empty=document.createElement('p');empty.textContent='还没有作品。写下一个方向，开始第一首。';list.append(empty);return}for(const job of jobs){const article=document.createElement('article');article.className='yue2-job';const head=document.createElement('div');head.className='yue2-job-head';const title=document.createElement('strong');title.textContent=job.style.length>46?job.style.slice(0,46)+'…':job.style;const badge=document.createElement('span');badge.textContent={queued:'等待中',running:'生成中',completed:'已完成',failed:'失败'}[job.status]||job.status;head.append(title,badge);const time=document.createElement('time');time.textContent=new Date(job.createdAt).toLocaleString('zh-CN');article.append(head,time);if(job.error){const p=document.createElement('p');p.textContent=job.error;article.append(p)}if(job.audioAvailable){const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.crossOrigin='use-credentials';audio.src=BASE+'/tools/yue2/jobs/'+job.id+'/audio';article.append(audio);if(job.durationSeconds){const p=document.createElement('p');p.textContent='时长 '+Math.round(job.durationSeconds)+' 秒';article.append(p)}}if(job.score){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='查看旋律与和弦计划';const pre=document.createElement('pre');pre.textContent=job.score;details.append(summary,pre);article.append(details)}list.append(article)}}
async function refresh(){try{const data=await api('/tools/yue2/jobs');jobs=data.jobs;$('workspace').hidden=false;$('login').hidden=true;$('submit').disabled=busy||!data.canSubmit;if(!data.canSubmit)status(data.adminOnly?'音乐生成正在内部测试':'音乐生成暂未开放');render()}catch(error){$('workspace').hidden=true;$('login').hidden=false;$('login').querySelector('p').textContent=error.message}}
$('generate-form').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;$('submit').disabled=true;status('正在提交…');try{const style=$('style').value.trim(),lyrics=$('lyrics').value.trim();await api('/tools/yue2/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({style,lyrics})});status('任务已提交，正在等待生成');await refresh()}catch(error){status(error.message)}finally{busy=false;await refresh()}};
refresh();setInterval(()=>{if(document.visibilityState==='visible'&&jobs.some(job=>['queued','running'].includes(job.status)))refresh()},5000);
})();
