(()=>{'use strict';
const BASE=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:3100/api':'https://api.junaf.com/api';
const $=id=>document.getElementById(id);let busy=false,refreshing=false,enabled=false,workerOnline=false,jobs=[],previewUrl=null;
async function api(path,options={},timeoutMs=30000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(BASE+path,{credentials:'include',cache:'no-store',signal:controller.signal,...options});const data=await response.json().catch(()=>({}));if(!response.ok){const error=Error(data.message||`请求失败 (${response.status})`);error.status=response.status;throw error}return data}catch(error){if(error.name==='AbortError')throw Error('连接超时，请稍后重试');throw error}finally{clearTimeout(timer)}}
function status(s){$('status').textContent=s}function button(){const pending=jobs.some(j=>['uploading','queued','running'].includes(j.status));$('submit').disabled=busy||!enabled||!workerOnline||pending;$('submit').textContent=busy?'正在上传…':'生成口播视频 ↗'}
function render(){const box=$('job-list');box.replaceChildren();if(!jobs.length){const p=document.createElement('p');p.textContent='还没有作品。选择人物素材和口播音频开始。';box.append(p);return}for(const job of jobs){const article=document.createElement('article');article.className='comfy-job';const head=document.createElement('div');head.className='comfy-job-head';const title=document.createElement('strong');title.textContent=job.sourceType==='mp4'?'视频人物素材':'静态人物素材';const badge=document.createElement('span');badge.textContent={uploading:'上传中',queued:'等待中',running:'生成中',completed:'已完成',failed:'失败'}[job.status]||job.status;head.append(title,badge);article.append(head);const time=document.createElement('time');time.textContent=new Date(job.createdAt).toLocaleString('zh-CN');article.append(time);if(job.error){const p=document.createElement('p');p.textContent=job.error;article.append(p)}if(job.videoAvailable){const url=BASE+'/tools/musetalk/jobs/'+job.id+'/video';const video=document.createElement('video');video.controls=true;video.playsInline=true;video.preload='none';video.crossOrigin='use-credentials';video.src=url;article.append(video);const link=document.createElement('a');link.href=url;link.download='junaf-musetalk-'+job.id+'.mp4';link.textContent='下载 MP4 ↗';link.className='comfy-download';article.append(link)}if(['uploading','queued','failed','completed'].includes(job.status)){const del=document.createElement('button');del.type='button';del.textContent='删除任务与文件';del.onclick=async()=>{if(!confirm('删除这条任务及已上传或生成的文件？'))return;try{await api('/tools/musetalk/jobs/'+job.id,{method:'DELETE'});await refresh()}catch(error){status(error.message)}};article.append(document.createTextNode(' · '),del)}box.append(article)}}
async function refresh(){if(refreshing)return;refreshing=true;try{const data=await api('/tools/musetalk/jobs');$('workspace').hidden=false;$('login').hidden=true;$('restricted').hidden=true;enabled=!!data.enabled;workerOnline=!!data.workerOnline;jobs=Array.isArray(data.jobs)?data.jobs:[];render();if(!busy)status(!enabled?'数字人口播尚未开放':!workerOnline?'5090 GPU 当前未连接，开机并启动工作进程后此页面会自动恢复。':jobs.some(j=>['queued','running'].includes(j.status))?'任务正在生成，页面会自动更新。':'准备就绪')}catch(error){if(error.status===401){$('workspace').hidden=true;$('login').hidden=false;$('restricted').hidden=true}else if(error.status===403){$('workspace').hidden=true;$('login').hidden=true;$('restricted').hidden=false}else status(error.message)}finally{refreshing=false;button()}}
$('source').onchange=()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);const f=$('source').files[0],box=$('source-preview');box.replaceChildren();if(!f){box.textContent='选择正面、清晰、无遮挡的人物画面';return}previewUrl=URL.createObjectURL(f);const view=document.createElement(f.type==='video/mp4'?'video':'img');view.src=previewUrl;if(view.tagName==='VIDEO'){view.muted=true;view.controls=true}view.alt='人物素材预览';box.append(view)};
$('generate-form').onsubmit=async event=>{event.preventDefault();if(busy||!enabled||!workerOnline)return;const source=$('source').files[0],audio=$('audio').files[0];if(!source||!['image/png','image/jpeg','image/webp','video/mp4'].includes(source.type)||source.size>40*1024*1024){status('请上传 40 MB 以下的 PNG/JPG/WebP 或 MP4 人物素材');return}if(!audio||!['audio/wav','audio/mpeg','audio/mp4','audio/x-m4a'].includes(audio.type)||audio.size>15*1024*1024){status('请上传 15 MB 以下的 WAV/MP3/M4A 口播音频');return}busy=true;button();let id=null;try{status('正在创建任务…');id=(await api('/tools/musetalk/jobs',{method:'POST'})).job.id;status('正在上传人物素材…');await api('/tools/musetalk/jobs/'+id+'/source',{method:'PUT',headers:{'Content-Type':source.type},body:source},120000);status('正在上传口播音频…');await api('/tools/musetalk/jobs/'+id+'/audio',{method:'PUT',headers:{'Content-Type':audio.type},body:audio},120000);await api('/tools/musetalk/jobs/'+id+'/submit',{method:'POST'});status('任务已提交，等待 5090 GPU 生成。');$('generate-form').reset();$('source-preview').textContent='选择正面、清晰、无遮挡的人物画面'}catch(error){status(error.message+'；如任务停留在“上传中”，可在结果区删除后重试。')}finally{busy=false;await refresh()}};
refresh();setInterval(()=>{if(document.visibilityState==='visible')refresh()},5000);
})();
