(()=>{'use strict';
const BASE=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:3100/api':'https://api.junaf.com/api';
const $=id=>document.getElementById(id);
const state={conversations:[],active:null,busy:false,available:true};
async function api(path,options={}){const response=await fetch(BASE+path,{credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.message||'请求失败，请稍后重试');return data}
function status(message){$('status').textContent=message}
function selected(){return state.conversations.find(item=>item.id===state.active)}
function render(){const current=selected();$('conversation-list').replaceChildren();for(const item of state.conversations){const wrap=document.createElement('div');wrap.className='chat-item'+(item.id===state.active?' active':'');const button=document.createElement('button');button.type='button';button.textContent=item.title;button.onclick=()=>{state.active=item.id;render()};wrap.append(button);$('conversation-list').append(wrap)}$('conversation-title').textContent=current?.title||'新的对话';$('delete-chat').hidden=!current;$('messages').replaceChildren();if(!current?.messages?.length){const empty=document.createElement('div');empty.className='chat-empty';empty.innerHTML='<span>JUNAF / DIALOGUE</span><h2>从一个问题开始。</h2><p>可以讨论创意、学习或工作中的想法。回答可能有误，请核对重要信息。</p>';$('messages').append(empty)}else for(const message of current.messages){const article=document.createElement('article');article.className='chat-message '+message.role;const label=document.createElement('small');label.textContent=message.role==='user'?'YOU / 你':'JUNAF / 智能对话';const content=document.createElement('div');content.className='content';content.textContent=message.content;article.append(label,content);$('messages').append(article)}$('messages').scrollTop=$('messages').scrollHeight}
async function init(){try{const data=await api('/tools/chat/conversations');state.conversations=data.conversations;state.available=data.available;$('workspace').hidden=false;$('login').hidden=true;if(!state.available)status('智能对话尚未配置');render()}catch(error){$('workspace').hidden=true;$('login').hidden=false;$('login').querySelector('p').textContent=error.message}}
$('new-chat').onclick=()=>{state.active=null;render();$('prompt').focus()};
$('delete-chat').onclick=async()=>{if(!state.active||!confirm('删除这组对话？'))return;try{await api('/tools/chat/conversations/'+state.active,{method:'DELETE'});state.conversations=state.conversations.filter(item=>item.id!==state.active);state.active=null;render();status('对话已删除')}catch(error){status(error.message)}};
$('chat-form').onsubmit=async event=>{event.preventDefault();if(state.busy)return;const message=$('prompt').value.trim();if(!message)return;state.busy=true;$('send').disabled=true;status('正在思考…');try{const data=await api('/tools/chat/messages',{method:'POST',body:JSON.stringify({conversationId:state.active,message})});const conversation=data.conversation;state.conversations=[conversation,...state.conversations.filter(item=>item.id!==conversation.id)];state.active=conversation.id;$('prompt').value='';render();status('已保存到账号')}catch(error){status(error.message)}finally{state.busy=false;$('send').disabled=false}};
init();
})();
