(()=>{'use strict';
const BASE=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:3100/api':'https://api.junaf.com/api';
const $=id=>document.getElementById(id);
const state={conversations:[],active:null};
async function api(path,options={}){let response;try{response=await fetch(BASE+path,{credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'},...options})}catch{throw Error('暂时无法读取对话记录，请稍后重试')}const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.message||'请求失败，请稍后重试');return data}
function status(message){$('status').textContent=message}
function selected(){return state.conversations.find(item=>item.id===state.active)}
function render(){const current=selected();$('conversation-list').replaceChildren();for(const item of state.conversations){const wrap=document.createElement('div');wrap.className='chat-item'+(item.id===state.active?' active':'');const button=document.createElement('button');button.type='button';button.textContent=item.title;button.onclick=()=>{state.active=item.id;render()};wrap.append(button);$('conversation-list').append(wrap)}$('conversation-title').textContent=current?.title||'选择过往对话';$('delete-chat').hidden=!current;$('messages').replaceChildren();if(!current?.messages?.length){const empty=document.createElement('div');empty.className='chat-empty';empty.innerHTML='<span>JUNAF / DIALOGUE</span><h2>过往记录</h2><p>通用对话实验已暂停。JUNAF 继续建设自己的思考结构与创作工具。</p>';$('messages').append(empty)}else for(const message of current.messages){const article=document.createElement('article');article.className='chat-message '+message.role;const label=document.createElement('small');label.textContent=message.role==='user'?'YOU / 你':'JUNAF / 智能对话';const content=document.createElement('div');content.className='content';content.textContent=message.content;article.append(label,content);$('messages').append(article)}$('messages').scrollTop=$('messages').scrollHeight}
async function init(){try{const data=await api('/tools/chat/conversations');state.conversations=data.conversations;$('workspace').hidden=false;$('login').hidden=true;render()}catch(error){$('workspace').hidden=true;$('login').hidden=false;$('login').querySelector('p').textContent=error.message}}
$('delete-chat').onclick=async()=>{if(!state.active||!confirm('删除这组对话？'))return;try{await api('/tools/chat/conversations/'+state.active,{method:'DELETE'});state.conversations=state.conversations.filter(item=>item.id!==state.active);state.active=null;render();status('对话已删除')}catch(error){status(error.message)}};
init();
})();
